version: '2.0'
services:

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  kinto:
    image: kinto/kinto-server:9.0.1
    command: sh -c "kinto migrate --ini /etc/kinto/kinto.ini && kinto start --ini /etc/kinto/kinto.ini --port 8888"
    links:
      - postgres
    ports:
      - "8888:8888"
    environment:
      # FIXME move to config/kinto.ini
      KINTO_CACHE_BACKEND: kinto.core.cache.postgresql
      KINTO_CACHE_URL: postgres://postgres:postgres@postgres/postgres
      KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
      KINTO_STORAGE_URL: postgres://postgres:postgres@postgres/postgres
      KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
      KINTO_PERMISSION_URL: postgres://postgres:postgres@postgres/postgres
    volumes:
      - ./config:/etc/kinto
